[major][patch] upgrade cloure-compiler to latest
BranchMetrics/web-branch-deep-linking-attribution pull request #870
Opened 2023-02-13 05:31 UTC by branch-nchoudry

## Description
The current version of google-closure-compiler `20220601.0.0` is outdated and vulnerable to CVE-2022-25647. 

Change release note - https://github.com/google/closure-compiler/releases/tag/v20230206

Fixes # (issue)
Upgrade google-closure-compiler to `20230206.0.0` to patch CVE-2022-25647.

## Type of change

Please delete options that are not relevant. - **TBD**
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Pre-commit lint checks
- [ ] Unit test - TBD
- [ ] Integration test - TBD

## JS Budget Check

Please mention the size in kb before abd after this PR - TBD

| Files            | Before      | After       | 
| -----------      | ----------- | ----------- |
| dist/build.js.   |             |      164KB       |
| dist/build.min.js|             |      74KB       |

## Checklist:
**TBD**
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings

## Mentions: 
List the person or team responsible for reviewing proposed changes.

cc @BranchMetrics/saas-sdk-devs for visibility.

2023-02-13 05:34 UTC, branch-nchoudry commented
FYI - Request from `firstcard.app`

2023-02-14 18:33 UTC, JagadeeshKaricherla-branch requested changes

2023-02-15 05:27 UTC, branch-nchoudry commented on package.json
>  		"google-closure-deps": "^20220502.0.0",
Done, please review!

2023-02-15 17:50 UTC, JagadeeshKaricherla-branch commented
LGTM

2023-02-15 17:50 UTC, merged

2023-02-21 19:45 UTC, dmelo commented
@branch-nchoudry , do you know when this is planned to be released?

2023-02-23 06:45 UTC, branch-nchoudry commented
> @branch-nchoudry , do you know when this is planned to be released?

We will release these changes next week. Thanks!

2023-03-06 14:10 UTC, dmelo commented
@branch-nchoudry , any update on publishing this PR?

2023-03-13 20:00 UTC, dmelo commented
Hi @branch-nchoudry. Do you have any updates?

2023-03-13 20:02 UTC, JagadeeshKaricherla-branch commented
We are currently testing these changes and will make a release post testing.

2023-03-28 12:17 UTC, dmelo commented
Hi @JagadeeshKaricherla-branch and @branch-nchoudry , any updates about when this will be released?

2023-03-28 16:50 UTC, JagadeeshKaricherla-branch commented
This is included in our latest release.